# Generated by Django 3.2.5 on 2021-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.AddField(
            model_name='article',
            name='article_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil əlavə et'),
        ),
    ]
