# Generated by Django 3.2.5 on 2021-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210714_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', verbose_name='Şəkil əlavə et', width_field='width_field'),
        ),
    ]
