# Generated by Django 3.2.5 on 2021-07-14 13:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210714_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='article',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[300, 500], upload_to='', verbose_name='Şəkil əlavə et'),
        ),
    ]
