# Generated by Django 3.2.5 on 2021-07-15 10:26

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210714_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[700, 450], upload_to='', verbose_name='Şəkil əlavə et'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_authpr', models.CharField(max_length=50, verbose_name='Ad')),
                ('comment_content', models.CharField(max_length=400, verbose_name='Rəy')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='Meqale')),
            ],
        ),
    ]
