# Generated by Django 3.2.5 on 2021-07-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_comment_authpr_comment_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
